# Generated by Django 2.1.2 on 2018-10-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=200, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Moneta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.FloatField()),
                ('nazionalita', models.CharField(max_length=30)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('posseduta', models.BooleanField(default=False, null=True)),
                ('da_scambiare', models.BooleanField(default=False, null=True)),
                ('da_acquistare', models.BooleanField(default=False, null=True)),
                ('prezzo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneta', models.ForeignKey(on_delete='DO_NOTHING', to='collezione.Moneta')),
            ],
        ),
        migrations.CreateModel(
            name='Scambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=40)),
                ('data_nascita', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('affidabilita', models.IntegerField(default=0)),
                ('iban', models.CharField(max_length=27, null=True)),
                ('collezionista', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scambio',
            name='contraenti',
            field=models.ManyToManyField(to='collezione.Utente'),
        ),
        migrations.AddField(
            model_name='scambio',
            name='monete',
            field=models.ManyToManyField(through='collezione.Offerta', to='collezione.Moneta'),
        ),
        migrations.AddField(
            model_name='offerta',
            name='offerente',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='collezione.Utente'),
        ),
        migrations.AddField(
            model_name='offerta',
            name='scambio',
            field=models.ForeignKey(on_delete='CASCADE', to='collezione.Scambio'),
        ),
        migrations.AddField(
            model_name='moneta',
            name='utente',
            field=models.ForeignKey(on_delete='CASCADE', to='collezione.Utente'),
        ),
        migrations.AddField(
            model_name='messaggio',
            name='destinatario',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='destinatario', to='collezione.Utente'),
        ),
        migrations.AddField(
            model_name='messaggio',
            name='mittente',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='mittente', to='collezione.Utente'),
        ),
        migrations.AddField(
            model_name='acquisto',
            name='collezionista',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='acquisto_collezionista', to='collezione.Utente'),
        ),
        migrations.AddField(
            model_name='acquisto',
            name='moneta',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='collezione.Moneta'),
        ),
        migrations.AddField(
            model_name='acquisto',
            name='venditore',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', related_name='acquisto_venditore', to='collezione.Utente'),
        ),
    ]
