# Generated by Django 2.1.2 on 2018-10-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='password',
        ),
    ]
