# Generated by Django 2.1.2 on 2018-10-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0002_auto_20181016_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utente',
            old_name='user_id',
            new_name='user',
        ),
    ]
