# Generated by Django 2.1.2 on 2018-10-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0003_auto_20181016_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='collezionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acquisto_collezionista', to='collezione.Utente'),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='moneta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collezione.Moneta'),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='venditore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acquisto_venditore', to='collezione.Utente'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to='collezione.Utente'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='mittente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mittente', to='collezione.Utente'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collezione.Utente'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='moneta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collezione.Moneta'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='offerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collezione.Utente'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='scambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collezione.Scambio'),
        ),
    ]
