# Generated by Django 2.1.2 on 2018-10-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0005_auto_20181016_1248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moneta',
            unique_together={('nazionalita', 'valore', 'utente')},
        ),
    ]
