# Generated by Django 2.1.2 on 2018-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0006_auto_20181017_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneta',
            name='foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
