# Generated by Django 2.1.2 on 2018-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0007_auto_20181018_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggio',
            name='letto',
            field=models.BooleanField(default=False),
        ),
    ]
