# Generated by Django 2.1.2 on 2018-10-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0008_messaggio_letto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possiede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posseduta', models.BooleanField(default=False, null=True)),
                ('da_scambiare', models.BooleanField(default=False, null=True)),
                ('da_acquistare', models.BooleanField(default=False, null=True)),
                ('prezzo', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moneta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='possiede',
            name='moneta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collezione.Moneta'),
        ),
        migrations.AddField(
            model_name='possiede',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collezione.Utente'),
        ),
        migrations.RemoveField(
            model_name='moneta',
            name='da_acquistare',
        ),
        migrations.RemoveField(
            model_name='moneta',
            name='da_scambiare',
        ),
        migrations.RemoveField(
            model_name='moneta',
            name='posseduta',
        ),
        migrations.RemoveField(
            model_name='moneta',
            name='prezzo',
        ),
        migrations.RemoveField(
            model_name='moneta',
            name='utente',
        ),
        migrations.AddField(
            model_name='moneta',
            name='utente',
            field=models.ManyToManyField(through='collezione.Possiede', to='collezione.Utente'),
        ),
    ]
