# Generated by Django 2.1.2 on 2018-10-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0009_auto_20181023_0936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moneta',
            unique_together={('valore', 'nazionalita')},
        ),
    ]
