# Generated by Django 2.1.2 on 2018-10-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0010_auto_20181023_1522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='possiede',
            unique_together={('utente', 'moneta')},
        ),
    ]
