# Generated by Django 2.1.2 on 2018-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0012_auto_20181025_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambio',
            name='monetaOfferta',
        ),
        migrations.AddField(
            model_name='scambio',
            name='monetaRichiesta',
            field=models.ManyToManyField(related_name='monetaRichiesta', to='collezione.Moneta'),
        ),
    ]
