# Generated by Django 2.1.2 on 2018-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0013_auto_20181025_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambio',
            name='monetaControOfferta',
            field=models.ManyToManyField(null=True, related_name='monetaControOfferta', to='collezione.Moneta'),
        ),
    ]
