# Generated by Django 2.1.2 on 2018-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0014_auto_20181025_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambio',
            name='monetaControOfferta',
            field=models.ManyToManyField(related_name='monetaControOfferta', to='collezione.Moneta'),
        ),
    ]
