# Generated by Django 2.1.2 on 2018-10-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0015_auto_20181025_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambio',
            name='monetaControOfferta',
        ),
        migrations.AddField(
            model_name='scambio',
            name='monetaControOfferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monetaControOfferta', to='collezione.Moneta'),
        ),
        migrations.RemoveField(
            model_name='scambio',
            name='monetaRichiesta',
        ),
        migrations.AddField(
            model_name='scambio',
            name='monetaRichiesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monetaRichiesta', to='collezione.Moneta'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='scambio',
            name='offerente',
        ),
        migrations.AddField(
            model_name='scambio',
            name='offerente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offerente', to='collezione.Utente'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='scambio',
            name='ricevente',
        ),
        migrations.AddField(
            model_name='scambio',
            name='ricevente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ricevente', to='collezione.Utente'),
            preserve_default=False,
        ),
    ]
