# Generated by Django 2.1.2 on 2018-10-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0016_auto_20181025_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambio',
            name='confermaOfferente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scambio',
            name='confermaRicevente',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
