# Generated by Django 2.1.2 on 2018-10-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0017_auto_20181025_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambio',
            name='votoOfferente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scambio',
            name='votoRicevente',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
