# Generated by Django 2.1.2 on 2018-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0018_auto_20181030_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambio',
            name='votoOfferente',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='scambio',
            name='votoRicevente',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
