# Generated by Django 2.1.2 on 2018-10-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0020_auto_20181030_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambio',
            name='votoOfferente',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='scambio',
            name='votoRicevente',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
