# Generated by Django 2.1.2 on 2018-10-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0021_auto_20181030_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='affidabilita',
            field=models.FloatField(default=0),
        ),
    ]
