# Generated by Django 2.1.2 on 2018-11-02 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0022_auto_20181030_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisto',
            name='prezzo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='possiede',
            name='prezzo',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
