# Generated by Django 2.1.2 on 2018-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0023_auto_20181102_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisto',
            name='votoCollezionista',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='acquisto',
            name='votoVenditore',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
