# Generated by Django 2.1.2 on 2018-11-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezione', '0024_auto_20181102_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='affidabilita',
        ),
    ]
